-- Run with `supabase db push` or apply in the Supabase SQL editor.
alter table public.activities add column if not exists is_archived boolean not null default false;
alter table public.accomplishment_reports add column if not exists is_archived boolean not null default false;

-- Required by the app's organization_evaluations upsert conflict target.
create unique index if not exists organization_evaluations_org_school_year_uidx
  on public.organization_evaluations (organization_id, school_year);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text not null,
  status text,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

alter table public.notifications enable row level security;
drop policy if exists "Users can read their own notifications" on public.notifications;
create policy "Users can read their own notifications" on public.notifications
  for select to authenticated using (recipient_id = auth.uid());
drop policy if exists "Users can mark their own notifications read" on public.notifications;
create policy "Users can mark their own notifications read" on public.notifications
  for update to authenticated using (recipient_id = auth.uid()) with check (recipient_id = auth.uid());

create or replace function public.notify_activity_change()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  should_notify boolean;
  event_title text;
  event_status text;
begin
  should_notify := TG_OP = 'INSERT' or OLD.status is distinct from NEW.status;
  if not should_notify then return NEW; end if;
  event_title := coalesce(NEW.title, 'GPOA activity');
  event_status := coalesce(NEW.status, 'Pending');

  if TG_OP = 'INSERT' then
    insert into public.notifications(recipient_id, title, body, status)
    select p.id, 'New GPOA submission', event_title || ' was submitted for review.', event_status
    from public.profiles p where p.role = 'Admin';
  else
    insert into public.notifications(recipient_id, title, body, status)
    select p.id, 'GPOA status updated', event_title || ' is now ' || event_status || '.', event_status
    from public.profiles p
    where p.organization_id = NEW.organization_id and p.role in ('President', 'Adviser');
  end if;
  return NEW;
end;
$$;

drop trigger if exists activities_notify_change on public.activities;
create trigger activities_notify_change after insert or update of status on public.activities
  for each row execute function public.notify_activity_change();

create or replace function public.notify_report_change()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  should_notify boolean;
  report_title text;
  report_status text;
begin
  should_notify := TG_OP = 'INSERT' or OLD.status is distinct from NEW.status;
  if not should_notify then return NEW; end if;
  report_title := coalesce(NEW.title, 'Accomplishment report');
  report_status := coalesce(NEW.status, 'Pending');
  if TG_OP = 'INSERT' then
    insert into public.notifications(recipient_id, title, body, status)
    select p.id, 'New accomplishment report', report_title || ' was submitted for review.', report_status
    from public.profiles p where p.role = 'Admin';
  else
    insert into public.notifications(recipient_id, title, body, status)
    select p.id, 'Accomplishment report updated', report_title || ' is now ' || report_status || '.', report_status
    from public.profiles p
    where p.organization_id = NEW.organization_id and p.role in ('President', 'Adviser');
  end if;
  return NEW;
end;
$$;

drop trigger if exists accomplishment_reports_notify_change on public.accomplishment_reports;
create trigger accomplishment_reports_notify_change after insert or update of status on public.accomplishment_reports
  for each row execute function public.notify_report_change();

-- Enable Supabase Realtime for the live in-app notification inbox.
do $$ begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then null;
end $$;
